[workspace]
members = [
    "modules/actix_web_helper",
    "modules/adder",
    "modules/postgres",
    "base",
    "web_api",
    "output",
    "libs/cookie-rs",
    "module_def_generator",
]

[replace]
"cookie:0.10.1" = { path = "libs/cookie-rs" }

